import os
import datetime
import re
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_PATH = os.path.join(BASE_DIR, '../incident-response/postmortem-template.md')
OUTPUT_DIR = os.path.join(BASE_DIR, '../incident-response/postmortems')
CONFIG_PATH = os.path.join(BASE_DIR, '../incident-response/config/metadata.json')

def slugify(text):
    text = text.lower()
    return re.sub(r'[\W_]+', '-', text).strip('-')

def load_metadata():
    if os.path.exists(CONFIG_PATH):
        try:
            with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"Warning: Could not load metadata.json: {e}")
    return {}

def main():
    print("--- SRE Postmortem Generator ---")
    
    # 0. Load Metadata
    metadata = load_metadata()
    service_name = metadata.get("service_name", "Unknown-Service")
    team_name = metadata.get("team_name", "Unknown-Team")
    emails = ", ".join(metadata.get("notification_emails", []))
    tags = ", ".join(metadata.get("auto_tags", []))

    print(f"Loaded Context: Service={service_name}, Team={team_name}")

    # 1. Gather Input
    title = input("Enter Incident Title (e.g. Login Failure): ").strip()
    if not title:
        print("Error: Title is required.")
        return

    severity = input("Enter Severity (SEV-1, SEV-2...): ").strip().upper()
    authors = input("Enter Authors (comma separated): ").strip()
    
    # 2. Prepare Metadata
    today = datetime.date.today().isoformat() # YYYY-MM-DD
    filename = f"{today}-{slugify(title)}.md"
    output_path = os.path.join(OUTPUT_DIR, filename)

    # 3. Read Template
    if not os.path.exists(TEMPLATE_PATH):
        print(f"Error: Template not found at {TEMPLATE_PATH}")
        return

    with open(TEMPLATE_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    # 4. Inject Metadata & Replace Placeholders
    # We will construct a new header with more info
    header = f"""# Postmortem: {title}
> **Auto-Generated by SRE Bot**

**Service:** {service_name} | **Team:** {team_name}
**Date:** {today}
**Authors:** {authors}
**Severity:** {severity}
**Tags:** {tags}
**Notifications Sent To:** {emails}

---
"""
    # Remove the generic header lines from template to avoid duplication if present
    # This is a simple scrape to remove the top generic block if it matches known structure
    # For now, we just append the template content below our rich header.
    
    # Filter out lines commonly found in the raw template top block to replace them cleanly
    lines = content.splitlines()
    cleaned_content = []
    skip_header = True
    for line in lines:
        if line.startswith("**Date:** YYYY") or line.startswith("**Authors:**") or line.startswith("**Status:**") or line.startswith("**Severity:** ["):
            continue
        cleaned_content.append(line)
    
    final_body = "\n".join(cleaned_content)
    
    # 5. Write File
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header + final_body)

    print(f"\nSUCCESS! Postmortem created at:\n{os.path.abspath(output_path)}")
    print(f"info: Action required -> Check {emails} for automated routing rules.")

if __name__ == "__main__":
    main()
